version: '3.9'

services:
  todo-app:
    build: ./
    command: ["./app"]
    ports:
      - "8080:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HTTP_ADDR=${HTTP_ADDR}
      - POSTGRES_CONNECT_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASS=${REDIS_PASS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    volumes:
      - ./.env:/app/.env

  db: #second container
    restart: always #when will the db restart
    image: postgres:14 #image for container
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment: #var env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5436:5432"